name: Mirror Production to Main

on:
  push:
    branches:
      - production

jobs:
  mirror:
    name: Mirror production to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Mirror production to main
        run: |
          git checkout production
          git pull origin production
          git push origin production:main --force
